[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
port = 8501

[theme]
primaryColor = "#4F46E5"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
font = "sans serif"

[client]
toolbarMode = "off"
showErrorDetails = false
